import os

OLLAMA_MODEL = "llama3"
OLLAMA_TIMEOUT = 180

XLSX_COLUMNS = [
    "(Ne pas modifier) Container",
    "(Ne pas modifier) Somme de contrôle de la ligne",
    "(Ne pas modifier) Modifié le",
    "N° Container",
    "N° TAN",
    "Item (N° TAN) (Commande)",
    "Compagnie maritime",
    "Port  (N° TAN) (Commande)",
    "Transitaire (N° TAN) (Commande)",
    "Date shipment",
    "Date accostage",
    "Statut Container",
    "Container size",
    "Date livraison",
    "Site livraison",
    "Date dépotement",
    "Modifié par",
    "Modifié le",
    "Date début Surestarie",
    "Date restitution estimative",
    "Nbr jours surestarie estimés",
    "Coût Surestaries Estimé (USD)",
    "Nbr jours perdu en douane",
    "Coût Surestaries Estimé (DZD)",
    "Nbr jours restants pour surestarie",
    "Nbr jours surestarie",
    "Coût Surestaries Réel (USD)",
    "Coût Surestaries Réel (DZD)",
    "Date réstitution",
    "Réstitué par (Camion)",
    "Réstitué par (Chauffeur)",
    "Centre de réstitution",
    "Check dépotement- restitution",
    "Check livraison-dépotement",
    "Check livraison-restitution",
    "Check Shipment-Accostage",
    "Créé le",
    "Créé par",
    "Check avis d'arrivée-restitution",
    "Taux de change*",
    "Livré par (Camion)",
    "Livré par (Chauffeur)",
    "Montant facturé (check)",
    "Nbr jour surestarie Facturé",
    "Montant facturé (DA)",
    "N° Facture compagnie maritime",
    "Commentaire",
    "Date declaration douane",
    "Date liberation douane",
]
